# Generated by Django 4.0.4 on 2022-05-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_height_userprofile_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(null=True, verbose_name='Height [m]'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(null=True, verbose_name='Weight [kg]'),
        ),
    ]
