# Generated by Django 4.0.4 on 2022-05-18 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Equipment')),
                ('description', models.TextField(max_length=1023, null=True, verbose_name='Equipment Description')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True, verbose_name='Exercise type')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Exercise')),
                ('level', models.SmallIntegerField(choices=[(0, 'Beginner'), (1, 'Intermediate'), (2, 'Upper-Intermediate'), (3, 'Advanced')], default=0, verbose_name='Exercise Level')),
                ('equipment', models.ManyToManyField(null=True, to='training.equipment', verbose_name='Equipment Needed')),
                ('ex_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.exercisetype', verbose_name='Exercise Type')),
            ],
            options={
                'ordering': ('name', 'level'),
            },
        ),
    ]
