# Generated by Django 4.0.4 on 2022-05-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.ManyToManyField(to='training.equipment', verbose_name='Equipment Needed'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='level',
            field=models.CharField(choices=[(0, 'Beginner'), (1, 'Intermediate'), (2, 'Upper-Intermediate'), (3, 'Advanced')], default=0, max_length=125, verbose_name='Exercise Level'),
        ),
    ]
